// Game: g1
addMemeStat(GabrieleMiani26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(GabrieleMiani26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(GabrieleMiani26,"g1","Birra offerta","Birra offerta",9);
addMemeStat(GabrieleMiani26,"g1","Spaccata","Spaccata",1);
addMemeStat(GabrieleMiani26,"g1","Intervista","Intervista pagina instagram",3);
addMemeStat(DavidGaspardo26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(AlessandroRizzi26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(AlessandroRizzi26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(MarcoLombardo26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(FilippoPasquon26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(FilippoPasquon26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(FilippoPasquon26,"g1","Intervista","Intervista pagina instagram",3);
addMemeStat(VittorioGri26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(VittorioGri26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(VittorioGri26,"g1","Birra offerta","Birra offerta",9);
addMemeStat(VittorioBasso26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(EnricoBravin26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(EnricoBravin26,"g1","Birra in panca","Birra in panca",3);
addMemeStat(EnricoBravin26,"g1","Birra offerta","Birra offerta",9);
addMemeStat(EnricoBravin26,"g1","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(LucaDonati26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(LucaDonati26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(LucaDonati26,"g1","Rookie","Bonus rookie",3);
addMemeStat(MarcoRizzi26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MarcoRizzi26,"g1","Birra in panca","Birra in panca",2);
addMemeStat(DanieleGanzit26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(GiacomoSilvestri26,"g1","Ingresso in campo","Ingresso in campo",2);
addMemeStat(GiacomoSilvestri26,"g1","Birra in panca","Birra in panca",3);
addMemeStat(AntonioGri26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(AntonioGri26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(FrancescoSchiavone26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(FrancescoSchiavone26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(FrancescoSchiavone26,"g1","Under","Bonus under",2);
addMemeStat(NicolaCollavini26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(NicolaCollavini26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(NicolaCollavini26,"g1","Under","Bonus under",2);
addMemeStat(LeonardoTirelli26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(LeonardoTirelli26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(LeonardoTirelli26,"g1","Under","Bonus under",2);
addMemeStat(MattiaCollavini26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MattiaCollavini26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(MattiaCollavini26,"g1","Rookie","Bonus rookie",3);
addMemeStat(JacopoLoPiccolo26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(JacopoLoPiccolo26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(JacopoLoPiccolo26,"g1","Rookie","Bonus rookie",3);
addMemeStat(JacopoLoPiccolo26,"g1","Under","Bonus under",2);
addMemeStat(ThomasGrillo26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(ThomasGrillo26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(ThomasGrillo26,"g1","Rookie","Bonus rookie",3);
addMemeStat(LuigiValentino26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(LuigiValentino26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(LuigiValentino26,"g1","Rookie","Bonus rookie",3);
addMemeStat(LuigiValentino26,"g1","Under","Bonus under",2);
addMemeStat(AlessandroParona26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(AlessandroParona26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(AlessandroParona26,"g1","Rookie","Bonus rookie",3);
addMemeStat(AlessandroParona26,"g1","Under","Bonus under",2);
addMemeStatCoach(NORD26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStatCoach(NORD26,"g1","Birra in panca","Birra in panca",2);
addMemeStat(GiovanniZanin26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(GiovanniZanin26,"g1","Over","Bonus over",1);
addMemeStat(PietroSoramel26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(PietroSoramel26,"g1","Intervista","Intervista pagina instagram",3);
addMemeStat(GiovanniTonizzo26,"g1","Ingresso in campo","Ingresso in campo",2);
addMemeStat(GiovanniTonizzo26,"g1","Intervista","Intervista pagina instagram",3);
addMemeStat(LucaSoramel26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(AlessandroSantin26,"g1","Under","Bonus under",2);
addMemeStat(StefanoPolano26,"g1","Over","Bonus over",3);
addMemeStat(PaoloZorzi26,"g1","Under","Bonus under",2);
addMemeStat(CristianFedrizzi26,"g1","Under","Bonus under",2);
addMemeStat(GabrieleAzzarone26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(MarcoComisso26,"g1","Birra in panca","Birra in panca",2);
addMemeStat(MarcoComisso26,"g1","Intervista","Intervista pagina instagram",3);
addMemeStat(MarcoComisso26,"g1","Over","Bonus over",1);
addMemeStat(AlessandroGalassi26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(NicholasComisso26,"g1","Rookie","Bonus rookie",3);
addMemeStat(NicholasComisso26,"g1","Under","Bonus under",2);
addMemeStat(BrunoMarchesi26,"g1","Rookie","Bonus rookie",3);
addMemeStatCoach(SUD26,"g1","Tenta una tripla","Tenta una tripla",1);
addMemeStat(GabrieleIndri26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MarcoSerrao26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MarcoSerrao26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(MarcoSerrao26,"g1","Over","Bonus over",1);
addMemeStat(WilliamIob26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(WilliamIob26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(MattiaMasotti26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MattiaMasotti26,"g1","Intervista","Intervista pagina instagram",3);
addMemeStat(MassimilianoRossi26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MassimilianoRossi26,"g1","Over","Bonus over",1);
addMemeStat(MattiaAnedda26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MattiaAnedda26,"g1","Birra in panca","Birra in panca",3);
addMemeStat(MattiaAnedda26,"g1","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(MattiaAnedda26,"g1","Speaker","Speaker",2);
addMemeStat(EdoardoPicogna26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(SamuelMasotti26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(SamuelMasotti26,"g1","Under","Bonus under",2);
addMemeStat(DavideBroggi26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(EnricoSant26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(EnricoSant26,"g1","Over","Bonus over",1);
addMemeStat(EugenioDeTina26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(EugenioDeTina26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(ThomasBaracetti26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(ThomasBaracetti26,"g1","Under","Bonus under",2);
addMemeStat(AlexMicottis26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(AlexMicottis26,"g1","Birra in panca","Birra in panca",2);
addMemeStat(MassimoMasotti26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MassimoMasotti26,"g1","Birra in panca","Birra in panca",2);
addMemeStat(LucaGemo26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(LucaGemo26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(LucaGemo26,"g1","Under","Bonus under",2);
addMemeStat(MauroPerina26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MatteoGrillo26,"g1","Ingresso in campo","Ingresso in campo",2);
addMemeStat(MatteoGrillo26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(LucaGrillo26,"g1","Ingresso in campo","Ingresso in campo",2);
addMemeStat(LucaGrillo26,"g1","Under","Bonus under",2);
addMemeStat(DenisVanin26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(DenisVanin26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(DenisVanin26,"g1","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(MarcoPolo26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MarcoPolo26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(MarcoGemo26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MarcoGemo26,"g1","Rookie","Bonus rookie",3);
addMemeStat(MarcoGemo26,"g1","Under","Bonus under",2);
addMemeStat(GabrieleVecciolini26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(GabrieleVecciolini26,"g1","Rookie","Bonus rookie",3);
addMemeStat(GabrieleVecciolini26,"g1","Under","Bonus under",2);
addMemeStat(PietroGioeleGolizia26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStat(PietroGioeleGolizia26,"g1","Rookie","Bonus rookie",3);
addMemeStat(PietroGioeleGolizia26,"g1","Under","Bonus under",2);
addMemeStatCoach(EST26,"g1","Ingresso in campo","Ingresso in campo",1);
addMemeStatCoach(EST26,"g1","Birra in panca","Birra in panca",1);
addMemeStatCoach(EST26,"g1","Abbigliamento escursionistico","Abbigliamento escursionistico",2);
addMemeStat(UmbertoNobile26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(MassimilianoMoretti26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(MassimilianoMoretti26,"g1","Birra offerta","Birra offerta",9);
addMemeStat(LarryTrevisan26,"g1","Ingresso in campo","Ingresso in campo",2);
addMemeStat(AlessandroSant26,"g1","Birra in panca","Birra in panca",3);
addMemeStat(MicheleDeAnna26,"g1","Birra in panca","Birra in panca",2);
addMemeStat(DevinChiarcos26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(AlessioFurlan26,"g1","Birra in panca","Birra in panca",1);
addMemeStat(ValentinoCigainero26,"g1","Birra in panca","Birra in panca",2);
addMemeStat(MatteoMargarit26,"g1","Over","Bonus over",1);
addMemeStat(SebastianoTonizzo26,"g1","Under","Bonus under",2);
addMemeStat(EmanueleCorleone26,"g1","Under","Bonus under",2);
addMemeStat(ChristianZanet26,"g1","Birra in panca","Birra in panca",2);
addMemeStat(ThomasDriussi26,"g1","Rookie","Bonus rookie",3);
addMemeStat(AlessandroNarduzzi26,"g1","Rookie","Bonus rookie",3);
addMemeStat(AlessandroNarduzzi26,"g1","Under","Bonus under",2);
addMemeStat(KevinGigante26,"g1","Rookie","Bonus rookie",3);
addMemeStat(KevinGigante26,"g1","Under","Bonus under",2);
addMemeStatCoach(WEST26,"g1","Birra offerta","Birra offerta",6);

// Game: g2
addMemeStat(GabrieleMiani26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(GabrieleMiani26,"g2","Birra offerta","Birra offerta",9);
addMemeStat(AlessandroRizzi26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(AlessandroRizzi26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(MarcoLombardo26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(MarcoLombardo26,"g2","Birra offerta","Birra offerta",9);
addMemeStat(MarcoLombardo26,"g2","Over","Bonus over",2);
addMemeStat(VittorioGri26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(VittorioGri26,"g2","Birra offerta","Birra offerta",9);
addMemeStat(EnricoBravin26,"g2","Ingresso in campo","Ingresso in campo",2);
addMemeStat(EnricoBravin26,"g2","Birra in panca","Birra in panca",3);
addMemeStat(EnricoBravin26,"g2","Birra offerta","Birra offerta",6);
addMemeStat(EnricoBravin26,"g2","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(LucaDonati26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(LucaDonati26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(LucaDonati26,"g2","Intervista","Intervista pagina instagram",3);
addMemeStat(MarcoRizzi26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(MarcoRizzi26,"g2","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(GiacomoSilvestri26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(GiacomoSilvestri26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(FrancescoSchiavone26,"g2","Under","Bonus under",2);
addMemeStat(NicolaCollavini26,"g2","Under","Bonus under",2);
addMemeStat(LeonardoTirelli26,"g2","Under","Bonus under",2);
addMemeStat(JacopoLoPiccolo26,"g2","Under","Bonus under",2);
addMemeStat(ThomasGrillo26,"g2","Under","Bonus under",2);
addMemeStatCoach(NORD26,"g2","Birra in panca","Birra in panca",2);
addMemeStatCoach(NORD26,"g2","Birra offerta","Birra offerta",3);
addMemeStat(FilippoSappa26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(GiovanniZanin26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(GiovanniZanin26,"g2","Over","Bonus over",1);
addMemeStat(GiacomoSpagnolo26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(PietroSoramel26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(PietroSoramel26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(PietroSoramel26,"g2","Birra offerta","Birra offerta",9);
addMemeStat(PietroSoramel26,"g2","Showtime","Showtime",1);
addMemeStat(GiovanniTonizzo26,"g2","Ingresso in campo","Ingresso in campo",3);
addMemeStat(GiovanniTonizzo26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(EmanueleDaneluzzi26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(LucaSoramel26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(LucaSoramel26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(StefanoPolano26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(PaoloZorzi26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(PaoloZorzi26,"g2","Tripla di tabella","Tripla di tabella",2);
addMemeStat(PaoloZorzi26,"g2","Intervista","Intervista pagina instagram",3);
addMemeStat(PaoloZorzi26,"g2","Under","Bonus under",2);
addMemeStat(CristianFedrizzi26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(CristianFedrizzi26,"g2","Under","Bonus under",2);
addMemeStat(GabrieleAzzarone26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(GabrieleAzzarone26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(MarcoComisso26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(MarcoComisso26,"g2","Birra offerta","Birra offerta",6);
addMemeStat(MarcoComisso26,"g2","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(MarcoComisso26,"g2","Showtime","Showtime",1);
addMemeStat(MarcoComisso26,"g2","Tripla di tabella","Tripla di tabella",2);
addMemeStat(MarcoComisso26,"g2","Over","Bonus over",1);
addMemeStat(AlessandroGalassi26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(NicholasComisso26,"g2","Under","Bonus under",2);
addMemeStat(GabrieleIndri26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(GabrieleIndri26,"g2","Intervista","Intervista pagina instagram",3);
addMemeStat(MarcoSerrao26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MarcoSerrao26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(MarcoSerrao26,"g2","Over","Bonus over",1);
addMemeStat(WilliamIob26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(WilliamIob26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(WilliamIob26,"g2","Birra offerta","Birra offerta",6);
addMemeStat(WilliamIob26,"g2","Cane in campo","Cane in campo",2);
addMemeStat(MattiaMasotti26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MattiaMasotti26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(MattiaMasotti26,"g2","Ankle breaker","Ankle breaker",1);
addMemeStat(MassimilianoRossi26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MassimilianoRossi26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(MassimilianoRossi26,"g2","Over","Bonus over",1);
addMemeStat(MattiaAnedda26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MattiaAnedda26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(MattiaAnedda26,"g2","Speaker","Speaker",2);
addMemeStat(EdoardoPicogna26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(EdoardoPicogna26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(SamuelMasotti26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(SamuelMasotti26,"g2","Under","Bonus under",2);
addMemeStat(DavideBroggi26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(DavideBroggi26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(EnricoSant26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(EugenioDeTina26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(EugenioDeTina26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(ThomasBaracetti26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(AlexMicottis26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(AlexMicottis26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(AlexMicottis26,"g2","Birra offerta","Birra offerta",9);
addMemeStat(AlexMicottis26,"g2","Buon compleanno","Buon compleanno",3);
addMemeStat(AlexMicottis26,"g2","Spara acqua a ivan","Spara acqua a ivan",1);
addMemeStat(AlexMicottis26,"g2","Over","Bonus over",1);
addMemeStat(MassimoMasotti26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MassimoMasotti26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(LucaGemo26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(LucaGemo26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(LucaGemo26,"g2","Over","Bonus over",2);
addMemeStat(MauroPerina26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MauroPerina26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(MatteoGrillo26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MatteoGrillo26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(MatteoGrillo26,"g2","Intervista","Intervista pagina instagram",3);
addMemeStat(LucaGrillo26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(LucaGrillo26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(DenisVanin26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(DenisVanin26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(MarcoPolo26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MarcoGemo26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MarcoGemo26,"g2","Ankle breaker","Ankle breaker",1);
addMemeStat(MarcoGemo26,"g2","Under","Bonus under",2);
addMemeStat(GabrieleVecciolini26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(GabrieleVecciolini26,"g2","Under","Bonus under",2);
addMemeStat(PietroGioeleGolizia26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(PietroGioeleGolizia26,"g2","Under","Bonus under",2);
addMemeStat(UmbertoNobile26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(MassimilianoMoretti26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(MassimilianoMoretti26,"g2","Birra offerta","Birra offerta",9);
addMemeStat(MassimilianoMoretti26,"g2","Intervista","Intervista pagina instagram",3);
addMemeStat(LarryTrevisan26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(LarryTrevisan26,"g2","Lascia maglia in campo","Lascia maglia in campo",-2);
addMemeStat(AlessandroCostantini26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(AlessandroCostantini26,"g2","Bandana","Bandana",1);
addMemeStat(AlessandroCostantini26,"g2","Intervista","Intervista pagina instagram",3);
addMemeStat(AlessandroSant26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(MicheleDeAnna26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(MicheleDeAnna26,"g2","Birra offerta","Birra offerta",9);
addMemeStat(DevinChiarcos26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(DevinChiarcos26,"g2","Birra in panca","Birra in panca",3);
addMemeStat(DevinChiarcos26,"g2","Birra offerta","Birra offerta",3);
addMemeStat(AlessioFurlan26,"g2","Birra in panca","Birra in panca",2);
addMemeStat(ValentinoCigainero26,"g2","Birra in panca","Birra in panca",3);
addMemeStat(ValentinoCigainero26,"g2","Birra offerta","Birra offerta",9);
addMemeStat(MatteoMargarit26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(MatteoMargarit26,"g2","Over","Bonus over",1);
addMemeStat(GiovanniDalFarra26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(SebastianoTonizzo26,"g2","Under","Bonus under",2);
addMemeStat(EmanueleCorleone26,"g2","Ingresso in campo","Ingresso in campo",1);
addMemeStat(ChristianZanet26,"g2","Birra in panca","Birra in panca",1);
addMemeStat(ThomasDriussi26,"g2","Under","Bonus under",2);
addMemeStatCoach(WEST26,"g2","Birra offerta","Birra offerta",6);

// Game: g3
addMemeStat(GabrieleMiani26,"g3","Birra in panca","Birra in panca",2);
addMemeStat(GabrieleMiani26,"g3","Birra offerta","Birra offerta",9);
addMemeStat(GabrieleMiani26,"g3","Pubblico in soccorso","Pubblico in soccorso",1);
addMemeStat(AlessandroRizzi26,"g3","Birra in panca","Birra in panca",1);
addMemeStat(VittorioGri26,"g3","Birra in panca","Birra in panca",2);
addMemeStat(VittorioGri26,"g3","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(VittorioGri26,"g3","Intervista","Intervista pagina instagram",3);
addMemeStat(EnricoBravin26,"g3","Ingresso in campo","Ingresso in campo",2);
addMemeStat(EnricoBravin26,"g3","Birra in panca","Birra in panca",2);
addMemeStat(EnricoBravin26,"g3","Birra offerta","Birra offerta",9);
addMemeStat(EnricoBravin26,"g3","Intervista","Intervista pagina instagram",3);
addMemeStat(LucaDonati26,"g3","Pubblico in soccorso","Pubblico in soccorso al fanta staff",1);
addMemeStat(MarcoRizzi26,"g3","Birra in panca","Birra in panca",2);
addMemeStat(MarcoRizzi26,"g3","Bandana","Bandana",1);
addMemeStat(DanieleGanzit26,"g3","Over","Bonus over",1);
addMemeStat(GiacomoSilvestri26,"g3","Birra in panca","Birra in panca",3);
addMemeStat(GiacomoSilvestri26,"g3","Intervista","Intervista pagina instagram",3);
addMemeStat(FrancescoSchiavone26,"g3","Under","Bonus under",2);
addMemeStat(NicolaCollavini26,"g3","Under","Bonus under",2);
addMemeStat(LeonardoTirelli26,"g3","Under","Bonus under",2);
addMemeStat(MattiaCollavini26,"g3","Tripla di tabella","Tripla di tabella",2);
addMemeStat(JacopoLoPiccolo26,"g3","Under","Bonus under",2);
addMemeStat(ThomasGrillo26,"g3","Under","Bonus under",2);
addMemeStat(LuigiValentino26,"g3","Under","Bonus under",2);
addMemeStat(AlessandroParona26,"g3","Tripla di tabella","Tripla di tabella",2);
addMemeStat(AlessandroParona26,"g3","Under","Bonus under",2);
addMemeStatCoach(NORD26,"g3","Birra in panca","Birra in panca",2);
addMemeStat(FilippoSappa26,"g3","Birra in panca","Birra in panca",1);
addMemeStat(FilippoSappa26,"g3","Pubblico in soccorso","Pubblico in soccorso al fanta staff",1);
addMemeStat(GiovanniZanin26,"g3","Birra in panca","Birra in panca",2);
addMemeStat(GiovanniZanin26,"g3","Shot","Shot",1);
addMemeStat(GiovanniZanin26,"g3","Minaccia con canna da pesca","Minaccia con canna da pesca",1);
addMemeStat(GiovanniZanin26,"g3","Over","Bonus over",1);
addMemeStat(GiacomoSpagnolo26,"g3","Ingresso in campo","Ingresso in campo",1);
addMemeStat(PietroSoramel26,"g3","Birra in panca","Birra in panca",2);
addMemeStat(PietroSoramel26,"g3","Birra offerta","Birra offerta",9);
addMemeStat(PietroSoramel26,"g3","Pubblico in soccorso","Pubblico in soccorso al fanta staff",1);
addMemeStat(PietroSoramel26,"g3","The truth","The truth",1);
addMemeStat(PietroSoramel26,"g3","Tripla di tabella","Tripla di tabella",2);
addMemeStat(GiovanniTonizzo26,"g3","Ingresso in campo","Ingresso in campo",3);
addMemeStat(LucaSoramel26,"g3","Birra in panca","Birra in panca",2);
addMemeStat(LucaSoramel26,"g3","Birra offerta","Birra offerta",9);
addMemeStat(LucaSoramel26,"g3","Pubblico in soccorso","Pubblico in soccorso al fanta staff",1);
addMemeStat(AlessandroSantin26,"g3","Under","Bonus under",2);
addMemeStat(StefanoPolano26,"g3","Under","Bonus under",3);
addMemeStat(JacopoTomasini26,"g3","Intervista","Intervista pagina instagram",3);
addMemeStat(PaoloZorzi26,"g3","Under","Bonus under",2);
addMemeStat(CristianFedrizzi26,"g3","Under","Bonus under",2);
addMemeStat(GabrieleAzzarone26,"g3","Birra in panca","Birra in panca",3);
addMemeStat(GabrieleAzzarone26,"g3","Tripla di tabella","Tripla di tabella",2);
addMemeStat(GabrieleAzzarone26,"g3","Intervista","Intervista pagina instagram",3);
addMemeStat(MarcoComisso26,"g3","Birra in panca","Birra in panca",3);
addMemeStat(MarcoComisso26,"g3","Birra offerta","Birra offerta",9);
addMemeStat(MarcoComisso26,"g3","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(MarcoComisso26,"g3","Birre offerte oltre il limite","Birre offerte oltre il limite",1);
addMemeStat(MarcoComisso26,"g3","Prel","Prel",1);
addMemeStat(MarcoComisso26,"g3","Over","Bonus over",1);
addMemeStat(AlessandroGalassi26,"g3","Birra in panca","Birra in panca",1);
addMemeStat(NicholasComisso26,"g3","Under","Bonus under",2);
addMemeStatCoach(SUD26,"g3","Birra in panca","Birra in panca",1);
addMemeStatCoach(SUD26,"g3","Birra offerta","Birra offerta",9);
addMemeStatCoach(SUD26,"g3","Birre offerte oltre il limite","Birre offerte oltre il limite",1);
addMemeStat(MarcoSerrao26,"g3","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MarcoSerrao26,"g3","Over","Bonus over",1);
addMemeStat(WilliamIob26,"g3","Birra offerta","Birra offerta",9);
addMemeStat(WilliamIob26,"g3","Torcicollo","Torcicollo",1);
addMemeStat(WilliamIob26,"g3","Intervista","Intervista pagina instagram",3);
addMemeStat(MattiaMasotti26,"g3","Birra offerta","Birra offerta",9);
addMemeStat(MattiaMasotti26,"g3","Intervista","Intervista pagina instagram",3);
addMemeStat(MassimilianoRossi26,"g3","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MassimilianoRossi26,"g3","Scopa curiosa","Scopa curiosa",1);
addMemeStat(MassimilianoRossi26,"g3","Over","Bonus over",1);
addMemeStat(MattiaAnedda26,"g3","Ingresso in campo","Ingresso in campo",3);
addMemeStat(MattiaAnedda26,"g3","Birra in panca","Birra in panca",2);
addMemeStat(MattiaAnedda26,"g3","Pubblico in soccorso","Pubblico in soccorso al fanta staff",1);
addMemeStat(MattiaAnedda26,"g3","Speaker","Speaker",2);
addMemeStat(EdoardoPicogna26,"g3","Birra in panca","Birra in panca",1);
addMemeStat(EdoardoPicogna26,"g3","Birra offerta","Birra offerta",9);
addMemeStat(EdoardoPicogna26,"g3","Pubblico in soccorso","Pubblico in soccorso al fanta staff",1);
addMemeStat(SamuelMasotti26,"g3","Ingresso in campo","Ingresso in campo",1);
addMemeStat(SamuelMasotti26,"g3","Under","Bonus under",2);
addMemeStat(EnricoSant26,"g3","Intervista","Intervista pagina instagram",3);
addMemeStat(EnricoSant26,"g3","Over","Bonus over",1);
addMemeStat(EugenioDeTina26,"g3","Birra in panca","Birra in panca",1);
addMemeStat(ThomasBaracetti26,"g3","Under","Bonus under",2);
addMemeStat(AlexMicottis26,"g3","Birra in panca","Birra in panca",2);
addMemeStat(AlexMicottis26,"g3","Birra offerta","Birra offerta",9);
addMemeStat(MassimoMasotti26,"g3","Birra in panca","Birra in panca",1);
addMemeStat(LucaGemo26,"g3","Birra in panca","Birra in panca",1);
addMemeStat(LucaGemo26,"g3","Over","Bonus over",2);
addMemeStat(MauroPerina26,"g3","Birra in panca","Birra in panca",1);
addMemeStat(MatteoGrillo26,"g3","Birra in panca","Birra in panca",1);
addMemeStat(LucaGrillo26,"g3","Birra in panca","Birra in panca",1);
addMemeStat(LucaGrillo26,"g3","Birra offerta","Birra offerta",6);
addMemeStat(DenisVanin26,"g3","Birra in panca","Birra in panca",1);
addMemeStat(MarcoPolo26,"g3","Birra in panca","Birra in panca",1);
addMemeStat(MarcoPolo26,"g3","Pubblico in soccorso","Pubblico in soccorso al fanta staff",2);
addMemeStat(MarcoGemo26,"g3","Under","Bonus under",2);
addMemeStat(PietroGioeleGolizia26,"g3","Under","Bonus under",2);
addMemeStatCoach(EST26,"g3","Ingresso in campo","Ingresso in campo",3);
addMemeStatCoach(EST26,"g3","Birra in panca","Birra in panca",1);
addMemeStatCoach(EST26,"g3","Vestito da pescatore","Vestito da pescatore",3);
addMemeStatCoach(EST26,"g3","2 su 2 con la rana","2 su 2 con la rana",2);
addMemeStat(UmbertoNobile26,"g3","Birra in panca","Birra in panca",2);
addMemeStat(UmbertoNobile26,"g3","Birra offerta","Birra offerta",9);
addMemeStat(MassimilianoMoretti26,"g3","Birra in panca","Birra in panca",2);
addMemeStat(MassimilianoMoretti26,"g3","Birra offerta","Birra offerta",9);
addMemeStat(MassimilianoMoretti26,"g3","Striscione invadente","Striscione invadente",1);
addMemeStat(AlessandroCostantini26,"g3","Birra in panca","Birra in panca",1);
addMemeStat(AlessandroCostantini26,"g3","Bandana","Bandana",1);
addMemeStat(AlessandroSant26,"g3","Birra in panca","Birra in panca",3);
addMemeStat(MicheleDeAnna26,"g3","Birra offerta","Birra offerta",9);
addMemeStat(MicheleDeAnna26,"g3","Intervista","Intervista pagina instagram",3);
addMemeStat(ValentinoCigainero26,"g3","Birra in panca","Birra in panca",2);
addMemeStat(ValentinoCigainero26,"g3","Birra offerta","Birra offerta",6);
addMemeStat(ValentinoCigainero26,"g3","Bandana","Bandana",1);
addMemeStat(ValentinoCigainero26,"g3","Striscione invadente","Striscione invadente",1);
addMemeStat(LucaDellaLonga26,"g3","Birra in panca","Birra in panca",1);
addMemeStat(MichaelMargarit26,"g3","Tripla di tabella","Tripla di tabella",2);
addMemeStat(SebastianoTonizzo26,"g3","Under","Bonus under",2);
addMemeStat(EmanueleCorleone26,"g3","Intervista","Intervista pagina instagram",3);
addMemeStat(EmanueleCorleone26,"g3","Under","Bonus under",2);
addMemeStat(ChristianZanet26,"g3","Birra in panca","Birra in panca",1);
addMemeStat(ThomasDriussi26,"g3","Under","Bonus under",2);
addMemeStat(AlessandroNarduzzi26,"g3","Under","Bonus under",2);
addMemeStat(KevinGigante26,"g3","Under","Bonus under",2);
addMemeStatCoach(WEST26,"g3","Birra offerta","Birra offerta",6);

// Game: semi
addMemeStat(GabrieleMiani26,"semi","Birra in panca","Birra in panca",1);
addMemeStat(GabrieleMiani26,"semi","Birra offerta","Birra offerta",9);
addMemeStat(GabrieleMiani26,"semi","Tat","Tat",1);
addMemeStat(GabrieleMiani26,"semi","Intervista","Intervista pagina instagram",3);
addMemeStat(AlessandroRizzi26,"semi","Ingresso in campo","Ingresso in campo",2);
addMemeStat(AlessandroRizzi26,"semi","Tat","Tat",1);
addMemeStat(VittorioGri26,"semi","Birra in panca","Birra in panca",3);
addMemeStat(VittorioGri26,"semi","Birra offerta","Birra offerta",9);
addMemeStat(VittorioGri26,"semi","Tat","Tat",1);
addMemeStat(VittorioGri26,"semi","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(VittorioBasso26,"semi","Tat","Tat",1);
addMemeStat(EnricoBravin26,"semi","Birra in panca","Birra in panca",3);
addMemeStat(EnricoBravin26,"semi","Birra offerta","Birra offerta",9);
addMemeStat(EnricoBravin26,"semi","Tat","Tat",1);
addMemeStat(LucaDonati26,"semi","Tat","Tat",1);
addMemeStat(LucaDonati26,"semi","Intervista","Intervista pagina instagram",3);
addMemeStat(MarcoRizzi26,"semi","Birra in panca","Birra in panca",3);
addMemeStat(MarcoRizzi26,"semi","Tat","Tat",1);
addMemeStat(MarcoRizzi26,"semi","Intervista","Intervista pagina instagram",3);
addMemeStat(GiacomoSilvestri26,"semi","Birra in panca","Birra in panca",2);
addMemeStat(GiacomoSilvestri26,"semi","Malus piangina","Malus piangina",-3);
addMemeStat(GiacomoSilvestri26,"semi","No look","No look",1);
addMemeStat(AntonioGri26,"semi","Tat","Tat",1);
addMemeStat(FrancescoSchiavone26,"semi","Under","Bonus under",2);
addMemeStat(NicolaCollavini26,"semi","Under","Bonus under",2);
addMemeStat(LeonardoTirelli26,"semi","Under","Bonus under",2);
addMemeStat(MattiaCollavini26,"semi","Birra in panca","Birra in panca",1);
addMemeStat(MattiaCollavini26,"semi","Tat","Tat",1);
addMemeStat(ThomasGrillo26,"semi","Under","Bonus under",2);
addMemeStat(AlessandroParona26,"semi","Under","Bonus under",2);
addMemeStat(FilippoSappa26,"semi","Birra in panca","Birra in panca",1);
addMemeStat(FilippoSappa26,"semi","Tripla di tabella","Tripla di tabella",2);
addMemeStat(GiovanniZanin26,"semi","Ingresso in campo","Ingresso in campo",3);
addMemeStat(GiovanniZanin26,"semi","Birra in panca","Birra in panca",2);
addMemeStat(GiovanniZanin26,"semi","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(GiovanniZanin26,"semi","Over","Bonus over",1);
addMemeStat(GiacomoSpagnolo26,"semi","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(PietroSoramel26,"semi","Birra in panca","Birra in panca",1);
addMemeStat(PietroSoramel26,"semi","Birra offerta","Birra offerta",9);
addMemeStat(GiovanniTonizzo26,"semi","Ingresso in campo","Ingresso in campo",3);
addMemeStat(EmanueleDaneluzzi26,"semi","Birra in panca","Birra in panca",2);
addMemeStat(AlessandroSantin26,"semi","Under","Bonus under",2);
addMemeStat(StefanoPolano26,"semi","Ingresso in campo","Ingresso in campo",3);
addMemeStat(StefanoPolano26,"semi","Over","Bonus over",3);
addMemeStat(PaoloZorzi26,"semi","Under","Bonus under",2);
addMemeStat(CristianFedrizzi26,"semi","Under","Bonus under",2);
addMemeStat(MarcoComisso26,"semi","Birra in panca","Birra in panca",2);
addMemeStat(MarcoComisso26,"semi","Birra offerta","Birra offerta",9);
addMemeStat(MarcoComisso26,"semi","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(MarcoComisso26,"semi","Over","Bonus over",1);
addMemeStat(NicholasComisso26,"semi","Under","Bonus under",2);
addMemeStatCoach(SUD26,"semi","Birra offerta","Birra offerta",9);
addMemeStatCoach(SUD26,"semi","Collaboratori (0.5x)","Collaboratori (0.5x)",4);
addMemeStatCoach(SUD26,"semi","Barber shop","Barber shop",2);
addMemeStatCoach(SUD26,"semi","Piegamenti","Piegamenti",1);
addMemeStatCoach(SUD26,"semi","Intervista","Intervista pagina instagram",3);
addMemeStat(GabrieleIndri26,"semi","Birra in panca","Birra in panca",1);
addMemeStat(GabrieleIndri26,"semi","Intervista","Intervista pagina instagram",3);
addMemeStat(MarcoSerrao26,"semi","Over","Bonus over",1);
addMemeStat(WilliamIob26,"semi","Ingresso in campo","Ingresso in campo",4);
addMemeStat(MattiaMasotti26,"semi","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MattiaMasotti26,"semi","Birra in panca","Birra in panca",1);
addMemeStat(MassimilianoRossi26,"semi","Birra in panca","Birra in panca",1);
addMemeStat(MassimilianoRossi26,"semi","Tiro libero di tabella","Tiro libero di tabella",2);
addMemeStat(MassimilianoRossi26,"semi","Over","Bonus over",1);
addMemeStat(SamuelMasotti26,"semi","Ingresso in campo","Ingresso in campo",1);
addMemeStat(SamuelMasotti26,"semi","Under","Bonus under",2);
addMemeStat(EnricoSant26,"semi","Over","Bonus over",1);
addMemeStat(ThomasBaracetti26,"semi","Under","Bonus under",2);
addMemeStat(AlexMicottis26,"semi","Ingresso in campo","Ingresso in campo",2);
addMemeStat(AlexMicottis26,"semi","Birra in panca","Birra in panca",1);
addMemeStat(LucaGemo26,"semi","Under","Bonus under",2);
addMemeStat(MatteoGrillo26,"semi","Birra in panca","Birra in panca",1);
addMemeStat(LucaGrillo26,"semi","Birra in panca","Birra in panca",1);
addMemeStat(DenisVanin26,"semi","Ingresso in campo","Ingresso in campo",2);
addMemeStat(DenisVanin26,"semi","Birra in panca","Birra in panca",1);
addMemeStat(DenisVanin26,"semi","Intervista","Intervista pagina instagram",3);
addMemeStat(MarcoGemo26,"semi","Under","Bonus under",2);
addMemeStat(PietroGioeleGolizia26,"semi","Under","Bonus under",2);
addMemeStatCoach(EST26,"semi","Maglia udinese","Maglia udinese",1);
addMemeStatCoach(EST26,"semi","Intervista","Intervista pagina instagram",3);
addMemeStat(UmbertoNobile26,"semi","Birra in panca","Birra in panca",1);
addMemeStat(MassimilianoMoretti26,"semi","Ingresso in campo","Ingresso in campo",1);
addMemeStat(MassimilianoMoretti26,"semi","Birra offerta","Birra offerta",9);
addMemeStat(MassimilianoMoretti26,"semi","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(MassimilianoMoretti26,"semi","Intervista","Intervista pagina instagram",3);
addMemeStat(AlessandroCostantini26,"semi","Ingresso in campo","Ingresso in campo",1);
addMemeStat(AlessandroCostantini26,"semi","Birra in panca","Birra in panca",1);
addMemeStat(AlessandroCostantini26,"semi","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(AlessandroCostantini26,"semi","Bandana","Bandana",1);
addMemeStat(AlessandroSant26,"semi","Birra in panca","Birra in panca",2);
addMemeStat(AlessandroSant26,"semi","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(MicheleDeAnna26,"semi","Birra in panca","Birra in panca",1);
addMemeStat(MicheleDeAnna26,"semi","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(AndreaMoretti26,"semi","Birra in panca","Birra in panca",2);
addMemeStat(AndreaMoretti26,"semi","Ankle breaker","Ankle breaker",1);
addMemeStat(ValentinoCigainero26,"semi","Birra in panca","Birra in panca",3);
addMemeStat(MatteoMargarit26,"semi","Birra in panca","Birra in panca",2);
addMemeStat(MatteoMargarit26,"semi","Vestito da cowboy","Vestito da cowboy",1);
addMemeStat(MiracleObichukwu26,"semi","Bandana","Bandana",1);
addMemeStat(GiacomoFerigo26,"semi","Birra in panca","Birra in panca",1);
addMemeStat(SebastianoTonizzo26,"semi","Under","Bonus under",2);
addMemeStat(EmanueleCorleone26,"semi","Ingresso in campo","Ingresso in campo",1);
addMemeStat(EmanueleCorleone26,"semi","Buzzer beater","Buzzer beater",1);
addMemeStat(EmanueleCorleone26,"semi","Tripla di tabella","Tripla di tabella",2);
addMemeStat(EmanueleCorleone26,"semi","Under","Bonus under",2);
addMemeStat(ChristianZanet26,"semi","Birra in panca","Birra in panca",1);
addMemeStat(ThomasDriussi26,"semi","Under","Bonus under",2);
addMemeStat(AlessandroNarduzzi26,"semi","Under","Bonus under",2);
addMemeStat(KevinGigante26,"semi","Under","Bonus under",2);
addMemeStatCoach(WEST26,"semi","Birra in panca","Birra in panca",1);
addMemeStatCoach(WEST26,"semi","Birra offerta","Birra offerta",6);
addMemeStatCoach(WEST26,"semi","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStatCoach(WEST26,"semi","Vestito da cowboy","Vestito da cowboy",1);

// Game: td3
addMemeStat(GabrieleMiani26,"td3","Birra offerta","Birra offerta",9);
addMemeStat(GabrieleMiani26,"td3","Porta da bere al tavolo","Porta da bere al tavolo",1);
addMemeStat(AlessandroRizzi26,"td3","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(AlessandroRizzi26,"td3","Intervista","Intervista pagina instagram",3);
addMemeStat(VittorioGri26,"td3","Birra offerta","Birra offerta",9);
addMemeStat(VittorioGri26,"td3","Moneyball incastrata","Moneyball incastrata",1);
addMemeStat(VittorioBasso26,"td3","Bandana","Bandana",1);
addMemeStat(EnricoBravin26,"td3","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(EnricoBravin26,"td3","Telefona con ciabatta","Telefona con ciabatta",1);
addMemeStat(LucaDonati26,"td3","Birra offerta","Birra offerta",9);
addMemeStat(LucaDonati26,"td3","Vince in ciabatte","Vince in ciabatte",10);
addMemeStat(LucaDonati26,"td3","Intervista","Intervista pagina instagram",3);
addMemeStat(MarcoRizzi26,"td3","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(GiacomoSilvestri26,"td3","Grembiule","Grembiule",3);
addMemeStat(MattiaCollavini26,"td3","Benda di hello kitty","Benda di hello kitty",3);
addMemeStat(MattiaCollavini26,"td3","Moneyball bendato","Moneyball bendato",3);
addMemeStat(MattiaCollavini26,"td3","Intervista","Intervista pagina instagram",3);
addMemeStatCoach(NORD26,"td3","Inoki indossa nord","Inoki indossa nord",3);
addMemeStat(FilippoSappa26,"td3","Pubblico in ciabatte","Pubblico in ciabatte",1);
addMemeStat(GiovanniZanin26,"td3","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(GiovanniZanin26,"td3","Arriva con la birra in mano","Arriva con la birra in mano",1);
addMemeStat(GiacomoSpagnolo26,"td3","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(EmanueleDaneluzzi26,"td3","Pubblico in ciabatte","Pubblico in ciabatte",1);
addMemeStat(LucaSoramel26,"td3","Grembiule","Grembiule",3);
addMemeStat(GabrieleAzzarone26,"td3","Benda di hello kitty","Benda di hello kitty",3);
addMemeStat(GabrieleAzzarone26,"td3","Moneyball bendato","Moneyball bendato",3);
addMemeStat(MarcoComisso26,"td3","Birra offerta","Birra offerta",9);
addMemeStat(MarcoComisso26,"td3","Intervista","Intervista pagina instagram",3);
addMemeStat(GabrieleIndri26,"td3","Pubblico in ciabatte","Pubblico in ciabatte",1);
addMemeStat(GabrieleIndri26,"td3","Intervista","Intervista pagina instagram",3);
addMemeStat(MarcoSerrao26,"td3","Aggiustatutto","Aggiustatutto",1);
addMemeStat(MarcoSerrao26,"td3","Sbirro est","Sbirro est",1);
addMemeStat(MattiaMasotti26,"td3","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(MattiaAnedda26,"td3","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(EdoardoPicogna26,"td3","Intervista","Intervista pagina instagram",3);
addMemeStat(EnricoSant26,"td3","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(DenisVanin26,"td3","Birra offerta","Birra offerta",6);
addMemeStat(UmbertoNobile26,"td3","Intervista","Intervista pagina instagram",3);
addMemeStat(MassimilianoMoretti26,"td3","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(MassimilianoMoretti26,"td3","Arriva col paloma","Arriva col paloma",1);
addMemeStat(AlessandroCostantini26,"td3","Grembiule","Grembiule",1);
addMemeStat(AlessandroCostantini26,"td3","Bandana","Bandana",1);
addMemeStat(AlessandroSant26,"td3","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(ValentinoCigainero26,"td3","Grembiule","Grembiule",3);
addMemeStat(GiacomoFerigo26,"td3","Pirata","Pirata",3);

// Game: final
addMemeStat(GabrieleMiani26,"final","Birra in panca","Birra in panca",1);
addMemeStat(GabrieleMiani26,"final","Too small","Too small",1);
addMemeStat(GabrieleMiani26,"final","Intervista","Intervista pagina instagram",3);
addMemeStat(AlessandroRizzi26,"final","Birra in panca","Birra in panca",2);
addMemeStat(AlessandroRizzi26,"final","Tat","Tat",1);
addMemeStat(AlessandroRizzi26,"final","Ci apre ombrello","Ci apre ombrello",3);
addMemeStat(AlessandroRizzi26,"final","Ankle breaker","Ankle breaker",1);
addMemeStat(AlessandroRizzi26,"final","Intervista","Intervista pagina instagram",3);
addMemeStat(FilippoPasquon26,"final","Più triple sbagliate totali","Più triple sbagliate totali",5);
addMemeStat(VittorioGri26,"final","Birra in panca","Birra in panca",2);
addMemeStat(VittorioGri26,"final","Birra offerta","Birra offerta",9);
addMemeStat(VittorioGri26,"final","Vichingo ferito","Vichingo ferito",1);
addMemeStat(VittorioBasso26,"final","Bandana","Bandana",1);
addMemeStat(VittorioBasso26,"final","Tat","Tat",1);
addMemeStat(EnricoBravin26,"final","Birra in panca","Birra in panca",4);
addMemeStat(EnricoBravin26,"final","Birra offerta","Birra offerta",9);
addMemeStat(EnricoBravin26,"final","Occhiali da sole in riscaldamento","Occhiali da sole nel riscaldamento",1);
addMemeStat(EnricoBravin26,"final","Mantello nel riscaldamento","Mantello nel riscaldamento",1);
addMemeStat(LucaDonati26,"final","Birra in panca","Birra in panca",2);
addMemeStat(LucaDonati26,"final","Tat","Tat",1);
addMemeStat(MarcoRizzi26,"final","Birra in panca","Birra in panca",5);
addMemeStat(MarcoRizzi26,"final","Tat","Tat",1);
addMemeStat(DanieleGanzit26,"final","Ingresso in campo","Ingresso in campo",5);
addMemeStat(GiacomoSilvestri26,"final","Birra in panca","Birra in panca",3);
addMemeStat(GiacomoSilvestri26,"final","Buon compleanno","Buon compleanno",3);
addMemeStat(GiacomoSilvestri26,"final","Tat","Tat",1);
addMemeStat(NicolaCollavini26,"final","Under","Bonus under",2);
addMemeStat(LeonardoTirelli26,"final","Under","Bonus under",2);
addMemeStat(MattiaCollavini26,"final","Birra in panca","Birra in panca",1);
addMemeStat(MattiaCollavini26,"final","Tat","Tat",1);
addMemeStatCoach(NORD26,"final","Malus piangina con tecnico","Malus piangina con tecnico",-3);
addMemeStat(MarcoComisso26,"final","Birra offerta","Birra offerta",9);
addMemeStat(WilliamIob26,"final","Birra offerta","Birra offerta",9);
addMemeStat(WilliamIob26,"final","Intervista","Intervista pagina instagram",3);
addMemeStatCoach(EST26,"final","Intervista","Intervista pagina instagram",3);
addMemeStat(MassimilianoMoretti26,"final","Birra in panca","Birra in panca",1);
addMemeStat(MassimilianoMoretti26,"final","Più tiri liberi sbagliati totali","Più tiri liberi sbagliati totali",5);
addMemeStat(MassimilianoMoretti26,"final","Intervista","Intervista pagina instagram",3);
addMemeStat(AlessandroCostantini26,"final","Ingresso in campo","Ingresso in campo",6);
addMemeStat(AlessandroCostantini26,"final","Bandana","Bandana",1);
addMemeStat(MicheleDeAnna26,"final","Ingresso in campo","Ingresso in campo",5);
addMemeStat(MicheleDeAnna26,"final","Intervista","Intervista pagina instagram",3);
addMemeStat(DevinChiarcos26,"final","Birra in panca","Birra in panca",2);
addMemeStat(AndreaMoretti26,"final","Birra in panca","Birra in panca",1);
addMemeStat(ValentinoCigainero26,"final","Birra in panca","Birra in panca",2);
addMemeStat(ValentinoCigainero26,"final","Elemosina","Elemosina",1);
addMemeStat(ValentinoCigainero26,"final","Intervista","Intervista pagina instagram",3);
addMemeStat(MatteoMargarit26,"final","Intervista","Intervista pagina instagram",3);
addMemeStat(MiracleObichukwu26,"final","Bandana","Bandana",1);
addMemeStatCoach(WEST26,"final","Intervista","Intervista pagina instagram",3);
